### ISSUE TITLE
NPE on /channel command when  no channels exist

### ISSUE THREAD

**Issue by Kiro47** [Chosencraft/ChosenChat#12]
[02:00:56 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'channel' in plugin ChosenChat v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-642f6d2-fbe3046]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-642f6d2-fbe3046]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot.jar:git-Spigot-642f6d2-fbe3046]  
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-642f6d2-fbe3046]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-642f6d2-fbe3046]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-642f6d2-fbe3046]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
        at com.chosen.www.chat.commands.Commands.getChannelStats(Commands.java:242) ~[?:?]
        at com.chosen.www.chat.commands.Commands.channelCommand(Commands.java:138) ~[?:?]
        at com.chosen.www.chat.commands.Commands.onCommand(Commands.java:101) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-642f6d2-fbe3046]
        ... 15 more

**Comment by theNewton17** [comment]
still working on reproducing this, I can't actually make it so no channels exist... I get an error when trying to delete the only channel so I'll fix that I guess

**Comment by theNewton17** [comment]
removed the ability to delete the General channel, so one channel will always exist now.
