### ISSUE TITLE
NPE on deleting channel with people still in it

### ISSUE THREAD

**Issue by Kiro47** [Chosencraft/ChosenChat#7]
When a channel is deleted that is anyones current channel they will indeed join the default general channel, however you also receive an NPE error.

```
[06:30:03 INFO]: Kiro47 issued server command: /channel delete help
[06:30:03 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'channel' in plugin ChosenChat v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_171]
        at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_171]
        at com.chosen.www.chat.commands.Commands.channelCommand(Commands.java:158) ~[?:?]
        at com.chosen.www.chat.commands.Commands.onCommand(Commands.java:80) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        ... 15 more

```

**Comment by theNewton17** [comment]
fixed. as it turns out, iterative for loops and foreach loops are not the same thing
