### ISSUE TITLE
Concurrent exception when using a local chat and nobody is in the local area

### ISSUE THREAD

**Issue by Kiro47** [Chosencraft/ChosenChat#9]
If a player is in a private channel and send a message with nobody within range it will throw an error and kick them out of their current channel into a new unspecified channel, and they can't talk to anybody until moving to a new channel.

```
[06:49:15 ERROR]: Could not pass event AsyncPlayerChatEvent to ChosenChat v1.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1319) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1257) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_171]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_171]
        at com.chosen.www.chat.events.EventClass.onChat(EventClass.java:95) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-2086bb0-8cc5a7e]
        ... 11 more

```

**Comment by theNewton17** [comment]
fixed, the list of recipients for a message was immutable because #blamenewts
